[project]
name = "babais-alg"
version = "0.1.0"
description = "Add your description here"
# readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # "numpy>=2.1.3",
    "pydantic-settings>=2.6.1",
    "typer>=0.13.1",
]

[project.scripts]
babais-alg = "babais_alg.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ['babais_alg']
